
package org.itmo.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarWebService", targetNamespace = "http://service.jaxws.ws.itmo.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarWebService {


    /**
     * 
     * @return
     *     returns java.util.List<genStandAlone.Car>
     */
    @WebMethod(operationName = "get-cars")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-cars", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandAlone.GetCars")
    @ResponseWrapper(localName = "get-carsResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandAlone.GetCarsResponse")
    public List<Car> getCars();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<genStandAlone.Car>
     */
    @WebMethod(operationName = "get-cars-by-params")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-cars-by-params", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandAlone.GetCarsByParams")
    @ResponseWrapper(localName = "get-cars-by-paramsResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandAlone.GetCarsByParamsResponse")
    public List<Car> getCarsByParams(
        @WebParam(name = "arg0", targetNamespace = "")
        Car arg0);

}
