
package org.itmo.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AuthorizationException", targetNamespace = "http://service.jaxws.ws.itmo.org/")
public class AuthorizationException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CarServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AuthorizationException(String message, CarServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AuthorizationException(String message, CarServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: genStandalone.CarServiceFault
     */
    public CarServiceFault getFaultInfo() {
        return faultInfo;
    }

}
