
package org.itmo.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarWebService", targetNamespace = "http://service.jaxws.ws.itmo.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarWebService {


    /**
     * 
     * @return
     *     returns java.util.List<genStandalone.Car>
     */
    @WebMethod(operationName = "get-cars")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-cars", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.GetCars")
    @ResponseWrapper(localName = "get-carsResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.GetCarsResponse")
    public List<Car> getCars();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<genStandalone.Car>
     */
    @WebMethod(operationName = "get-cars-by-params")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-cars-by-params", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.GetCarsByParams")
    @ResponseWrapper(localName = "get-cars-by-paramsResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.GetCarsByParamsResponse")
    public List<Car> getCarsByParams(
        @WebParam(name = "arg0", targetNamespace = "")
        Car arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "create-new-car")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create-new-car", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.CreateNewCar")
    @ResponseWrapper(localName = "create-new-carResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.CreateNewCarResponse")
    public Long createNewCar(
        @WebParam(name = "arg0", targetNamespace = "")
        Car arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "delete-car")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete-car", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.DeleteCar")
    @ResponseWrapper(localName = "delete-carResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.DeleteCarResponse")
    public Boolean deleteCar(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "update-car")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update-car", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.UpdateCar")
    @ResponseWrapper(localName = "update-carResponse", targetNamespace = "http://service.jaxws.ws.itmo.org/", className = "genStandalone.UpdateCarResponse")
    public Boolean updateCar(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Car arg1);

}
